INSERT INTO template.vendors(vendor)
VALUES ('private')
, ('eBay')
, ('Amazon')
, ('Toys R Us')
, ('Barnes & Noble')
, ('Best Buy')
, ('Michaels')
, ('Hot Topic')
, ('Entertainment Earth')
, ('Box Lunch')
, ('FYE')
, ('7 Bucks A Pop')
, ('BAIT')
, ('Gemini')
, ('Craigslist')
;
