INSERT INTO variations(variant) VALUES ('None')
, ('Metallic')
, ('Flocked')
, ('Glow in the Dark')
, ('Glitter')
, ('Diamond')
, ('Black & White')
, ('Silver')
, ('Gold')
, ('Clear')
, ('Bloody')
, ('Sepia')
, ('Silhouette')
, ('Patina')
, ('White Gamma')
, ('Blue Gamma')
, ('Green Gamma')
, ('Neon Magenta')
, ('Neon Lime')
, ('Neon Orange')
, ('Gray')
, ('Red')
, ('Blue')
, ('Purple')
, ('Chrome Purple')
;
