INSERT INTO exclusives(exclusive) VALUES ('N/a')
, ('Chase')
, ('Funko Shop')
, ('Hot Topic')
, ('Toys R Us')
, ('Gemini')
, ('Entertainment Earth')
, ('FYE')
, ('Convention Exclusive')
, ('Walmart')
, ('Thinkgeek')
, ('Target')
, ('Gamestop')
, ('Disney Store (Europe)')
, ('Popcultcha')
, ('Walgreens')
, ('Toy Matrix')
, ('Barnes & Noble')
, ('D23 Expo')
, ('Costco')
, ('San Diego Comic Con')
, ('Amazon')
, ('Collector Corps')
, ('Legion of Collectors')
, ('Previews')
, ('Loot Crate')
, ('Dallas Comic Con')
, ('Specialty Series')
, ('Disney Parks')
, ('Emerald City Comic Con')
, ('Box Lunch')
, ('Funko Fundays')
, ('Fugitive Toys')
, ('Bangkok Comic Con')
, ('Disney Store')
, ('LA Anime Expo')
, ('Funko Pop!-Up Shop')
, ('New York Comic Con')
, ('Singapore Airlines')
, ('ToyCon')
, ('Animation-Comic-Game Hong Kong')
, ('BAIT')
, ('Disney Treasures')
, ('Forbidden Planet')
, ('Australia')
, ('PX Previews')
;
