INSERT INTO series(series) VALUES ('Custom')
, ('Heroes')
, ('Marvel')
, ('Rocks')
, ('Television')
, ('Movies')
, ('Animation')
, ('Disney')
, ('Star Wars')
, ('Game of Thrones')
, ('JK Rowling')
, ('WWE')
, ('Games')
, ('Rides')
, ('Sports')
, ('Ad Icons')
, ('Board Games')
, ('Comics')
, ('8-Bit')
, ('Marvel vs Capcom')
, ('South Park')
, ('Originals')
, ('Monsters')
, ('Freddy Funko')
, ('Asia')
, ('Pets')
, ('My Little Pony')
, ('Sesame Street')
, ('Muppets')
, ('Holiday')
, ('Stan Lee')
, ('Books')
, ('Conan O''Brien')
, ('Ugly Dolls')
, ('DIY')
, ('Sanrio')
, ('Pop the Vote')
, ('Sci Fi')
, ('Classics')
, ('Royals')
, ('Drag Queens')
;
